---
- name: Prepare Nexus3 Pro
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create license file
      ansible.builtin.copy:
        content: "{{ lookup('env', 'NEXUS_LICENSE_B64') | b64decode }}"
        dest: "nexus.lic"
        mode: '0644'
      register: __license_status__
      # TODO: Need a fact to detmerine if we're already on pro version or not
      when: (lookup('env', 'NEXUS_LICENSE_B64') is defined or nexus_license_b64 is defined) and nexus_enable_pro

    - name: copy license to container
      community.docker.docker_container_copy_into:
        container: nexus3-pro
        path: nexus.lic
        container_path: /nexus-data/nexus.lic
        mode: 0755
      # TODO: Need a fact to detmerine if we're already on pro version or not
      when: (lookup('env', 'NEXUS_LICENSE_B64') is defined or nexus_license_b64 is defined) and nexus_enable_pro

    - name: copy license to container 2
      community.docker.docker_container_copy_into:
        container: nexus3-pro-2
        path: nexus.lic
        container_path: /nexus-data/nexus.lic
        mode: 0755
      # TODO: Need a fact to detmerine if we're already on pro version or not
      when: (lookup('env', 'NEXUS_LICENSE_B64') is defined or nexus_license_b64 is defined) and nexus_enable_pro

    # create nexus.properties file
    - name: Create nexus.properties file
      ansible.builtin.copy:
        content: |
          nexus.datastore.clustered.enabled = true
          nexus.licenseFile=/nexus-data/nexus.lic
        dest: "nexus.properties"
        mode: '0644'
      # TODO: Need a fact to detmerine if we're already on pro version or not
      when: (lookup('env', 'NEXUS_LICENSE_B64') is defined or nexus_license_b64 is defined) and nexus_enable_pro

    - name: copy nexus.properties to container
      community.docker.docker_container_copy_into:
        container: nexus3-pro
        path: nexus.properties
        container_path: /nexus-data/etc/nexus.properties
        mode: 0755
        force: true
      # TODO: Need a fact to detmerine if we're already on pro version or not
      when: (lookup('env', 'NEXUS_LICENSE_B64') is defined or nexus_license_b64 is defined) and nexus_enable_pro

    - name: copy nexus.properties to container 2
      community.docker.docker_container_copy_into:
        container: nexus3-pro-2
        path: nexus.properties
        container_path: /nexus-data/etc/nexus.properties
        mode: 0755
        force: true
      # TODO: Need a fact to detmerine if we're already on pro version or not
      when: (lookup('env', 'NEXUS_LICENSE_B64') is defined or nexus_license_b64 is defined) and nexus_enable_pro

    # - name: Gather facts about the nexus3-pro container
    #   community.docker.docker_container_info:
    #     name: nexus3-pro
    #   register: nexus3_info

    # - name: Set nexus3_ip variable
    #   ansible.builtin.set_fact:
    #     nexus3_ip: "{{ nexus3_info.container.NetworkSettings.Networks.nexus.IPAddress }}"

    - name: Wait for Nexus writable API endpoint to be available
      ansible.builtin.uri:
        url: "http://nexus3-pro:4081/service/rest/v1/status/writable"
        method: GET
        validate_certs: false
        status_code: 200
      register: __nexus_writable__
      until: __nexus_writable__.status == 200
      retries: 30
      delay: 10

    - name: Fetch the admin.password from the nexus3-oss container
      community.docker.docker_container_exec:
        container: nexus3-pro
        command: "cat /nexus-data/admin.password"
      register: __nexus_initial_admin_password__

    - name: Show the admin.password
      ansible.builtin.debug:
        var: __nexus_initial_admin_password__

    - name: Update password of admin user
      ansible.builtin.uri:
        url: "http://nexus3-pro:4081/service/rest/v1/security/users/admin/change-password"
        user: admin
        password: "{{ __nexus_initial_admin_password__.stdout }}"
        method: PUT
        force_basic_auth: true
        validate_certs: false
        status_code: 204
        headers:
          Content-Type: text/plain
          accept: application/json
        body: "changeme"
        body_format: raw

    - name: Disable Anonmous access
      ansible.builtin.uri:
        url: "http://nexus3-pro:4081/service/rest/v1/security/anonymous"
        user: admin
        password: changeme
        method: PUT
        force_basic_auth: true
        validate_certs: false
        status_code: 200
        body: |
          {
            "enabled": false,
            "userId": "anonymous",
            "realmName": "NexusAuthorizingRealm"
          }
        body_format: json

    - name: Remove license from file system
      ansible.builtin.file:
        path: "nexus.lic"
        state: absent

    # - name: Gather facts about the s3-storage-pro container
    #   community.docker.docker_container_info:
    #     name: s3-storage-pro
    #   register: s3_storage_info

    # - name: Set s3_storage_ip variable
    #   ansible.builtin.set_fact:
    #     s3_storage_ip: "{{ s3_storage_info.container.NetworkSettings.Networks.nexus.IPAddress }}"

    - name: Configure MinIO CLI
      ansible.builtin.command: |
        mc alias set s3-storage http://s3-storage-pro:9000 minioadmin minioadmin
      register: minio_cli_configured
      changed_when: "'s3-storage' not in minio_cli_configured.stdout"

    - name: Show minio_cli_configured
      ansible.builtin.debug:
        var: minio_cli_configured

    - name: Create S3 bucket in MinIO for Nexus
      ansible.builtin.command: >
        mc mb s3-storage/nexus-storage
      when: minio_cli_configured.stdout is not search('successfully')

    - name: Create new access keys (service account) for Nexus
      ansible.builtin.command: >
        mc admin user add s3-storage nexus-user nexus-password

    - name: Attach readwrite policy to new access keys
      command: >
        mc admin policy attach s3-storage readwrite --user nexus-user
      register: attach_policy_result

    - name: Create service account (access key) for existing user
      command: >
        mc admin user svcacct add s3-storage nexus-user --access-key nexus-access-key --secret-key nexus-secret-key
      register: svcacct_result
      tags: minio