---
name: Publish new version to Galaxy

on:
  push:
    branches:
      - main
    paths:
      - galaxy.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install -r requirements.txt

      - name: Build collection
        run: ansible-galaxy collection build
      - name: Trigger a new import on Galaxy.
        run: ansible-galaxy collection publish cloudkrafter-nexus-*.tar.gz --token ${{ secrets.GALAXY_API_KEY }}
